### ISSUE TITLE
Not an issue, PRAISE

### ISSUE THREAD

**Issue by YenBenGrey** [reonZ/mini-tracker#1]
This is amazing, I mean truly amazing. I can't find you in the Foundry Discord to SHOUT at you for how amazing this is. 

I watched a video recently about making combat more exciting by putting the enemies in between the players in initiative, and so far I have been opening each one and inputting a number. Dragging them round the tracker is GOLD! 

THANK YOU!! 

YenBenGrey

**Comment by reonZ** [comment]
thank you
