### ISSUE TITLE
[Feature Request] Client option for scale

### ISSUE THREAD

**Issue by roguedevjake** [reonZ/mini-tracker#11]
The tracker is a fair bit smaller than the popped out default tracker on my 4k monitor, just enough to be slightly uncomfortable.

Would it be possible to add a scale slider into the options that was client only? (rather than world)

It would impact:
- Tracker width (as height is automatic/scalable as is)
- Button height and width
- Text size

**Comment by reonZ** [comment]
I can take a look, i dunno how feasible it is though.

**Comment by reonZ** [comment]
`1.13.0`
-   added `Font Size` setting, the entire tracker will scale with it

It grows a tad wider that it should with higher font size, but it is the best i could do.
