### ISSUE TITLE
Mini Tracker resets position on turn change

### ISSUE THREAD

**Issue by weepingminotaur** [reonZ/mini-tracker#12]
Foundry v10, build 291, Pf2e 4.6.3

Clicking Next Turn on the Mini Tracker causes the tracker to reset position to the top left of the screen, even if it's currently somewhere else.

**Comment by reonZ** [comment]
I just played a 3 hours session on the same version as yours and nobody have reported that behavior, and i can't seem to be able to reproduce the problem on my end whatever i do.

**Comment by weepingminotaur** [comment]
Odd. Will see if I can reproduce it in a clean world.

**Comment by weepingminotaur** [comment]
Ugh, my error. For some reason the Sortable JS module wasn't on. Works fine now. Sorry for the false alarm.

**Comment by reonZ** [comment]
No worries, dependency modules are very poorly handled by the foundry, i have had "similar" issues quite often.
