### ISSUE TITLE
I am getting an error in one game world but not the other. 

### ISSUE THREAD

**Issue by YenBenGrey** [reonZ/mini-tracker#13]
Please can you help. When the Mini Tracker pops up it is always on the far top left of the screen and then when I try and drag it, it appears some way off to the right of where the cursor is. I have attached a screenshot of the console error. 

EDIT: every time I make a change to the mini-tracker it jumps to the far top left of the screen. Roll Init, add a combatant, etc...

Another EDIT: When I do Find the Culprit, and keep Mini Tracker live, it just says it is Mini Tracker which is baffling because my other game world has exactly the same set up as far as I can see. 

This only happens in one of my worlds, both DND5e. V10. 

![Screenshot 2023-01-09 at 23 40 26](https://user-images.githubusercontent.com/98095856/211430200-c35755a0-452a-4776-a7ca-93370077b800.png)

**Comment by reonZ** [comment]
Funny because you are the second person making an issue about that.

So your problem is that you don't have the module `Sortable` enabled.

**Comment by YenBenGrey** [comment]
That’s odd. I went through all the modules. SortableJS was there. I will check again. However thank you for replying.

**Comment by YenBenGrey** [comment]
Thank you that’s sorted it. Bizarre.
