### ISSUE TITLE
Request - option to specify character sheet location

### ISSUE THREAD

**Issue by ditzer252** [reonZ/mini-tracker#14]
First, your module is awesome so thank you for making and sharing it!
Would you please consider adding a feature/option so that if the character sheet opens automatically, the GM (or regular user) could specify the position of the sheet.  For example, when I play PF2e and I'm GMing with my laptop, I like to have each combatant's character sheet open automatically in the top left corner of the screen when it is their turn.  The functionality I'm hoping you might add is similar to the features in [Next-Up](https://github.com/kandashi/Next-Up), but that module hasn't been updated for a long time...
Thanks again!

**Comment by reonZ** [comment]
This is quite out of the scope of the module tbh, i don't think i am gonna implement it sorry.

**Comment by reonZ** [comment]
a bit of a necro but i have added a setting that saves the sheet location and another one that closes the sheet on turn change in the version `1.19.0`

**Comment by ditzer252** [comment]
Awesome.  Thank you!

The close sheet setting doesn’t seem to work.
