### ISSUE TITLE
PF2e: Cannot be enabled due to issues in required dependencies

### ISSUE THREAD

**Issue by roleoutgames** [reonZ/mini-tracker#15]
I use this module in D & D 5e with no issues. However, when trying to enable it for PF2e I get the error "Cannot be enabled due to issues in required dependencies". Is there a required module?

Foundry: 10.291
PF2e 4.6.8

**Comment by reonZ** [comment]
There is indeed.

![Foundry_Virtual_Tabletop_xtruSeng7S](https://user-images.githubusercontent.com/651462/214744251-5f7913c3-023b-4d97-9403-5465adde0475.jpg)

**Comment by roleoutgames** [comment]
Gotcha Thank you. I am running on forge and the dependencies didn't show up on the install page. But installed sortable and working like a charm again. Thank you!
