### ISSUE TITLE
Issue with Force Client Settings

### ISSUE THREAD

**Issue by weepingminotaur** [reonZ/mini-tracker#16]
Getting this red console error whenever I log into Foundry. It doesn't seem to affect functionality, but I figured I'd report it anyway, just to be safe.
<img width="612" alt="Screen Shot 2023-02-23 at 12 39 59 PM" src="https://user-images.githubusercontent.com/90105219/220989828-855bddf9-5c61-45a3-b821-9c64679d25ed.png">

**Comment by reonZ** [comment]
I changed just changed how mini tracker is compiled, there won't be anymore name scrambling (the unreadable chain of characters you see in your screen).

Please check again if you get the error and if so, i would love to see the error once again.
