### ISSUE TITLE
Feature Request - Only open to specific users/permission levels

### ISSUE THREAD

**Issue by lucaspicerni** [reonZ/mini-tracker#17]
Hello! Excellent module! It would be great if it was possible to set specific users for the Mini Tracker to appear automatically, like for example only the GM or only the players. Thanks!

**Comment by reonZ** [comment]
I don't understand the use case, why would you restrict your users to be able to use it ? It doesn't give away anything out of permission restriction.

**Comment by lucaspicerni** [comment]
For me the utility would be, for example, in a face-to-face game, where I don't want the Mini Tracker to be displayed to the user acting as a display, on a TV. Or in a stream setup, along the same lines.

**Comment by reonZ** [comment]
But you can disable the tracker on a per user base, just do that on the tab that is used for the display on the stream.

**Comment by lucaspicerni** [comment]
Okay, thanks!
