### ISSUE TITLE
Add alliance color & targeting toggle

### ISSUE THREAD

**Issue by meldogs** [reonZ/mini-tracker#18]
Version 4.10.0 of the PF2e system introduced two new additions to the encounter tracker.
(stwlam) Highlight row of encounter tracker's active turn with alliance color
(stwlam) Indicate which users are targeting combatants in Encounter Tracker, add targeting toggle
Could these be added to mini-tracker?

**Comment by reonZ** [comment]
I am not currently working on modules, but i think i will eventually implement something similar.

**Comment by LukasPrism** [comment]
I came here to pop it down for when Idle jumps back into things, but you beat me to it. Us 5E plebs are jealous of these advancements!

**Comment by reonZ** [comment]
Both features have been added to the version `1.15.0`
