### ISSUE TITLE
[Feature Request] Drag and Drop repositioning (pf2e)

### ISSUE THREAD

**Issue by roguedevjake** [reonZ/mini-tracker#19]
The default combat tracker has this enabled for pf2e but it doesn't seem to work on the mini tracker (if it has been added in the last couple of weeks forgive me) 

This is commonly used in PF2e and similar systems to allow for quickly resorting a delayed character (and moving unconscious characters if you aren't using pf2e workshop to automate it).

**Comment by reonZ** [comment]
https://github.com/reonZ/mini-tracker#change-initiative-by-dragging-combatant

This has been possible literally since my first release 8 months ago, you could have also just tried.

**Comment by roguedevjake** [comment]
> https://github.com/reonZ/mini-tracker#change-initiative-by-dragging-combatant
> 
> This has been possible literally since my first release 8 months ago, you could have also just tried.

You are rght, that is actually why I started using it (for 5e instead of combat enhancements so I could drop another module)
It certainly didn't work last session in pf2e, so maybe I have a conflict somewhere, I dunno... (I would normally check things again before posting but I am moving houses atm and just wanted to mention while I remembered again, sorry for the bother)

**Comment by reonZ** [comment]
Let me know if you still have issues, i just made another test on a server with pf2e system but i am on v11 now.
