### ISSUE TITLE
FEATURE REQUEST: Allow for not popping out the window

### ISSUE THREAD

**Issue by GambetTV** [reonZ/mini-tracker#20]
I use the module "Combat Focus," which allows me to see both the initiative window and the chat window at the same time (it puts the initiative window above the chat window), which saves a lot of space. I love all the features of this module, except that in order to use it I have to have the initiative window popped out, which just kind of unnecessarily takes up more space and is a less clean setup. I don't know if it would be possible, but if so, could you have an option that simply incorporates all of these settings into the main combat window, so that we don't have to have a duplicate pop-out window if we don't want to?

**Comment by reonZ** [comment]
Sorry, this module purposely doesn't touch the regular combat tracker.

Also this would require me to incorporate all the features manually once more but in a different context which is definitely not something i want to do and maintain.
