### ISSUE TITLE
Feature request : Pf2e Utility buttons integration

### ISSUE THREAD

**Issue by uniwars** [reonZ/mini-tracker#21]
Hi, would that be possible to add integration of the Pf2e Utility Button module delay buttons ?

![image](https://github.com/reonZ/mini-tracker/assets/65986545/c28592e3-e539-4954-8269-4ad4cdf54dc2)

https://github.com/oWave/pf2e-flatcheck-helper

I opened the same feature request for mini tracker as I don't know which need to implement the other.

**Comment by reonZ** [comment]
It would make more sense if you asked `PF2e Utility Button` to integrate with `Mini Tracker` instead
- mini tracker is a system agnostic module, it wouldn't make much sense if it was supporting a system specific module
- they are already integrating their stuff in the combat tracker so it should be fairly easy to do the same in the mini tracker
