### ISSUE TITLE
Feature request : Setting to pop the tracker expanded by default

### ISSUE THREAD

**Issue by uniwars** [reonZ/mini-tracker#24]
Hello again, sorry. I'm facing a riot because the tracker pops minimized and it seems to complicated to find the "maximize" button, and "when we hover the tracker it moves and expand itself it's bad"

(Même après avoir fait un tuto avec des screens et des flèches rouges ils continuent de pas être content "là il pop à la tronche avec la pire config possible" et voudraient avoir la même UX que vanilla par défaut)

**Comment by reonZ** [comment]
too complicated to find the maximize button, really ? sorry but this is really going beyond ridiculous here
