### ISSUE TITLE
[Feature request] Out Of Combat Tracker compatibility

### ISSUE THREAD

**Issue by lucaspicerni** [reonZ/mini-tracker#27]
Hello! It would be great if the Mini Tracker was compatible with the [Out Of Combat Tracker](https://gitlab.com/mxzf/ooct) module. It would be possible? Thanks!

**Comment by reonZ** [comment]
This is ofc debatable, but i tend to think that this kind of module should implement its features into the mini-tracker, since they are already doing a similar job when implementing them in the regular tracker.

In any case, i don't plan on making it, sorry.
