### ISSUE TITLE
Request: do not unhide combatants from tracker if their tokens remain hidden

### ISSUE THREAD

**Issue by dineshm72** [reonZ/mini-tracker#28]
Right now there are three options for hidden combatants:
1- Hide enemies when added
2- Reveal enemies at their first turn
3- Reveal the token's hidden state

IMO, ideally there would be a 4th option to reveal hidden state tokens in the tracker at their first turn (or else always don't do so).

My use case: typically, if I have a hidden token in the tracker, it's because I'm not sure if I'm ever going to add them to the combat, or because I plan to reveal them but not until rounds later, or maybe because they are doing hidden things during combat that the players are not aware of.  In general, I want them to stay hidden (both their token state, and their position in the tracker) until I unhide the token or decide to manually reveal them in the tracker.

Thanks for considering!

**Comment by reonZ** [comment]
i don't understand the issue, if you don't want tokens/combatants to be revealed automatically then don't use the option.

**Comment by dineshm72** [comment]
Sorry I didn't explain very clearly.  There are two kinda of enemy combatants that can get hidden:

1- Normal combatants who the party sees, like a bugbear you run into who screams at you and rushes in to attack.  In the default foundry workflow, the GM rolls their initiative, the party sees what the bugbear rolled, and where it fits in amongst all their initiative rolls, and they can plan tactically around that.  

An alternative workflow is one where the bugbear's initiative roll is hidden at first, and isn't revealed until his turn in the combat arrives.  It adds a bit of suspense, and makes it somewhat harder for the party to plan (at least in that first round), but that is all.  After that, their initiative is revealed to all.

You have two settings that make this possible - Hide Combatants to hide the initial roll, and Reveal Combatants to reveal it once their turn comes.  So far so good.

2- Enemies who are hidden, as in their token state is set to hidden in the HUD, and only the GM sees them.  In default foundry (I think, if memory serves), you can add these tokens to combat, and roll initiative for them, but their position in the initiative (and in fact their very existence in the combat) remains hidden to players until you unhide them.  You have to separately and manually unhide their tokens so they are visible on the canvas and can be targeted, and unhide their position/existence in the tracker too, so players can see when their turn comes up.

A GM may hide an enemy like this for a number of reasons.  I sometimes do it if I'm not sure if I want to use all the enemies I placed on the map during preparation - I will see how the fight goes before maybe bringing in a few extra combatants.  Or they might be set up to join the fight in waves.  Or they might just be hidden around a corner, aware of the players and casting stoneskin or other defensive spells first, before joining the fray and making players aware of them, and as GM I want to make sure they remain hidden until I choose to reveal them.  

In these cases, I may want these enemies taking a turn in the order or I may not.  But either way, I don't want them to be revealed to the players when their first turn in the order comes up, I want them to remain hidden until I choose to unhide them.

When adding them to combat they are hidden by default, so I don't even need an option to make that happen (I think, I'm not positive what would happen in mini tracker if I tried without the "Hide Combatant" option set, but I would generally have this set anyway).  But in order for them to remain hidden in both the initiative order and the canvas I need to make sure that the "Reveal Combatants" and "Reveal Tokens" options are both turned off.

--

Now, the issue is when I want both of the above to happen.  I want to add some suspense to the combat, and allow the enemies who are visible to remain hidden at first, but get revealed when they take their first turn.  But I also have some other combatants who are hidden tokens, and I want them to not get revealed when they take their first turn.  

Right now, there is only the one setting, so there is no way to reveal the "normal" combatants but not the token-hidden ones.  I'm asking for an option to separately decide whether to reveal those tokens.  (Or, if you prefer, use the "Reveal Tokens" option to also decide whether to reveal the token-hidden combatant in the combat log initiative order, since almost always if you don't want the token revealed, you also don't want it's initiative and existence revealed.)

If you decide not to implement this, the workaround is to just not add those token-hidden combatants to the combat at all until I'm ready to use them.  It's just easier to be able to add them all at once.

There may be one issue to address - whose turn do you show in the tracker for the players when a hidden combatant is taking their turn.  But you already have to address that one if you have Hide Combatants set but not Reveal Combatants.

Hopefully that makes sense.  Sorry so wordy.

**Comment by dineshm72** [comment]
I guess I should also add that the workflow I describe above is already possible using Monk's Combat Details.  But it stops working if I also use Mini Tracker, because your options override those options.

It also includes another convenience feature - when you unhide a token on the canvas, it will optionally also unhide the combatant in the tracker, so you no longer have to do both steps manually.

https://github.com/ironmonk88/monks-combat-details

**Comment by reonZ** [comment]
what i don't understand is how hiding the bugbear's initiative matters ? the number itself isn't important, its position in the tracker is and hiding the initiative value won't change that, players will still see where the bugbear stands in the tracker.

so in both cases you need to hide the bugbear combatant entirely from the tracker to have any impact and if you do, how can i differentiate which is supposed to be revealed and which one isn't ?

also, if another modules have those features you like, why don't you just disable the settings in `Mini Tracker` and let the other module handle it ?

**Comment by dineshm72** [comment]
I agree that hiding the bugbears initiative doesn't really matter too much, it's more a flavor thing.  And it doesn't have to be an enemy who they can already see, I was just using that as an example.  It might be the party turns a corner and can see one guy as the combat starts, but more enemies are hidden around another corner and about the join the fray (like Han Solo in the scene where he chases the stormtroopers around the corner before running into a whole platoon).

You can differentiate which should be revealed and which shouldn't by whether their tokens are set to hidden or not (and whether the "Reveal Tokens" option is set or not).

I thought your settings were overriding my other modules, but I just tested and keeping both is working fine.  So if this isn't something you'd want to implement, I can work around it.  Thanks!
