### ISSUE TITLE
Enhancement: close char sheet when turn ends

### ISSUE THREAD

**Issue by dineshm72** [reonZ/mini-tracker#29]
I love the option to open the char sheet when its a combatants turn.  It would be great if it would also close the sheet when that turn ends, to minimize the clutter on screen.  (And also remember the position so it will open again in the same position next turn.)

This is essentially recreating some of the functionality from an old module, Next Up.  You might find some other inspiration there too.  
https://github.com/kandashi/Next-Up

**Comment by reonZ** [comment]
both features were added in version `1.19.0`
