### ISSUE TITLE
Right Click Target

### ISSUE THREAD

**Issue by jputman** [reonZ/mini-tracker#3]
Add a right click on item and then target like the normal combat tracker allows so that if something is invisible you can target it even if you can't see the token.

**Comment by reonZ** [comment]
Sorry but i don't understand what you mean. Every mechanics on the original tracker are present in this one too, right-click included. Also if a creature is invisible, it doesn't appear in the tracker, so there is no interaction possible.

**Comment by jputman** [comment]
That doesn't seem to be 100% the case, the right click works as a GM but not as a player. 

I am using the invisible condition so that the player doesn't see the target on the map, but they can still see in the tracker.

I am attaching some screen shots.

GM View

![image](https://user-images.githubusercontent.com/9375319/204166380-aae0d631-c3cd-4d71-ac46-1acab16273d1.png)

Player View

![image](https://user-images.githubusercontent.com/9375319/204166395-52c598e0-8cd5-4b71-8309-01bcd0551861.png)

Right click on Combat tracker as player

![image](https://user-images.githubusercontent.com/9375319/204166412-bc4c2bc4-e25a-436a-8aa1-407cb4d13498.png)

Right click on mini tracker

![image](https://user-images.githubusercontent.com/9375319/204166423-42805952-abaf-4409-8c22-03dd698e844f.png)

Also, it seems that as a player I can't even right click on the owned token in the mini tracker.

**Comment by jputman** [comment]
I tested as well with just these modules to see if it was a conflict, but no change.

![image](https://user-images.githubusercontent.com/9375319/204166724-53cbcf66-4909-4c73-b531-ae3613c107b9.png)

**Comment by reonZ** [comment]
Alright, thanks for the detailed info, i will look into it.

**Comment by reonZ** [comment]
So i went and checked but as far as i can tell, this is not core behavior, i tested on both systems `dnd5e` and `pf2e` and a player can not right click on the combat tracker, there is no context menu.

What is your system ?

**Comment by jputman** [comment]
Ahh yes, it is being added by a module, and not sure why it still seemed to work even when I had disabled the module maybe it didn't refresh.

Seems to be added by monk's little details

**Comment by reonZ** [comment]
To be honest, i think i will try to add the ability for players to target a token from the tracker, i will work on that next.

**Comment by jputman** [comment]
Awesome. Thanks for the module in general, it is a great addition. It is these QoL things that make the platform great, and the community execellent.

**Comment by reonZ** [comment]
Players can now target from the tracker directly (a setting to disable the feature is available) with version 1.6.0
