### ISSUE TITLE
Request: add 2nd line for "next up" initiative, or some similar variation

### ISSUE THREAD

**Issue by dineshm72** [reonZ/mini-tracker#31]
I know the goal is to make the tracker slim, but a possible option to add might be to optionally add a second line to show who is coming up next in initiative, so that that person can see it and start to prepare their turn.  

Possibly highlighted in some way (colored fill?) for the player whose turn it is going to be, to make sure they notice.  

Alternative 1: Or it only pops out the second line if your client is the one who is next (so for everyone else it's one line)

Alternative 2: Instead of a line showing who is next, have a bar that simply tells you how many turns until your next turn, i.e. "You're up in 3 turns", "You're next!", something like that.  If a player controls multiple tokens (or if you're the GM) it would just show the next one for you.

**Comment by reonZ** [comment]
I can't have rows of different heights in the tracker, the whole dynamic part of the tracker is reliant on it having all rows identical.

Also, the next to play is the one after the row that is colored so, coloring 2 rows shouldn't be needed, unless you play in a 10 players group, this seem to be a very frivolous feature, players should be following what is happening during the combat even when it is not their turn.

**Comment by dineshm72** [comment]
I didn't mean rows of different heights (except alternative #2 could have been I suppose), I meant add a second normal row for whoever is next in the initiative.  So if there are 10 combatants, and we're on the 5th one, it would show the 5th and 6th ones.

This is for when the tracker is collapsed to just show the current initiative.  You can't look at the coloration then, it always shows the current turn with its color, but you can't see who is next.

Just clarifying, since I don't think you understood what I was asking for.  If you don't want to do it, of course that is fine.

**Comment by reonZ** [comment]
I see now, i will keep it in mind, maybe someday i will revisit the idea
