### ISSUE TITLE
Weird UI conflict with Anonymous

### ISSUE THREAD

**Issue by dineshm72** [reonZ/mini-tracker#32]
Having just Mini Tracker and Anonymous (plus libs) loaded causes a weird UI glitch, the Mini Tracker gets popped up to the upper left corner every time the tracker updates.

Just Mini Tracker works fine, I have it placed here:
<img width="365" alt="image" src="https://github.com/reonZ/mini-tracker/assets/2231877/a1ba3eac-8211-4e5e-97cf-4388836f1330">

Adding in Anonymous, and it glitches up to here:
<img width="274" alt="image" src="https://github.com/reonZ/mini-tracker/assets/2231877/1815356f-fde3-4ede-97a6-647f034466de">

But "it" still "thinks" it's in the right place.  If I click and drag it, it immediately moves back to where it's supposed to be, and as I drag the cursor around while dragging it stays offset by that distance.  I can't really screenshot this because my cursor disappears, but it's an inch or two above and to the left of the tracker (because that's where the tracker was supposed to be, relative to where I started clicking and dragging):
<img width="386" alt="image" src="https://github.com/reonZ/mini-tracker/assets/2231877/e79a6657-c4fd-440d-b893-1261c363b24f">

I don't really see any options in either one that could be adjusted to affect this.

**Comment by reonZ** [comment]
fixed in version `1.19.2`
