### ISSUE TITLE
Feature Request: Do not contract tracker when pointer is over advance turn/round buttons

### ISSUE THREAD

**Issue by MrPotatoZed** [reonZ/mini-tracker#5]
Love this mod and thanks for all your hard work on it. However, it would be awesome if moving to advance combat to the next turn or next round wouldn't cause the tracker to contract and thereby prevent us from advancing the tracker. Presently if you're hovering over combatants you have to move the pointer outside the tracker entirely and then move it onto the bottom of the tracker from a specific direction in order to prevent the buttons from "running away" from the pointer. Video with what I'm talking about below. The behavior is certainly not the end of the world but it's arguably less than ideal. One "fix" would be to make it such that hovering over the bar with the previous round/turn and next round/turn buttons wouldn't cause the tracker to contract regardless of which direction the pointer moved in from. With this option in place the tracker wouldn't contract unless the pointer left the the area of the tracker entirely. Thanks again!      
![minitracker](https://user-images.githubusercontent.com/85974617/204423315-b7be90b3-a469-4519-b56f-7ae9173d6534.gif)

**Comment by reonZ** [comment]
I will see what i can do about that.

I will need to change the way i handle the feature though, because right now i am using the CSS selector `:hover` and what you are asking is not possible with that.

**Comment by reonZ** [comment]
This has been "fixed" with version `1.6.4`
