### ISSUE TITLE
Feature Request: Disable expand on hover

### ISSUE THREAD

**Issue by roleoutgames** [reonZ/mini-tracker#7]
Can you add an option to disable the expand-on hover option altogether? I know you can set the delay to a very long time but I would like to disable the hover expand and keep expanding it manually with the button. Thanks for your consideration.

**Comment by reonZ** [comment]
Sure can do.

**Comment by reonZ** [comment]
There is now a setting `Expand on Hover` that you can disable added with version `1.8.5`
